---
AWSTemplateFormatVersion: 2010-09-09
Description: Terraform AWS pipeline
Parameters:
  RepoName:
    Type: String
    Description: Name for CodeCommit repository
  RepoBranch:
    Type: String
    Description: Name for repository branch to monitor
  BuilderProjectName:
    Type: String
    Description: Name for CodeBuild project
Resources:
  
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: Terraform repository

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: codecommit-policy
          PolicyDocument:
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "codecommit:CancelUploadArchive"
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:UploadArchive"
                
  BuilderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: s3-policy
          PolicyDocument:
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
        - PolicyName: cloudwatch-policy
          PolicyDocument:
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
        - PolicyName: codecommit-policy
          PolicyDocument:
            Statement:
              - Resource: !GetAtt Repository.Arn
                Effect: Allow
                Action:
                  - "codecommit:GitPull"
  ArtifactBucket:
    Type: AWS::S3::Bucket

  Builder:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref BuilderProjectName
      Description: A description about my project
      ServiceRole: !GetAtt BuilderRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8
      TimeoutInMinutes: 10

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref RepoName
                BranchName: !Ref RepoBranch
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuildOutput
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref BuilderProjectName

Outputs:
  RepoSSHClone:
    Description: Repository SSH URL
    Value: !GetAtt Repository.CloneUrlSsh
