---
AWSTemplateFormatVersion: 2010-09-09
Description: Terraform AWS pipeline
Parameters:
  RepoName:
    Type: String
    Description: Name for CodeCommitRepository
Resources:
  
  # CodeCommit repository
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: Terraform repository

  # CodePipeline

Outputs:
  RepoSSHClone:
    Description: Repository SSH URL
    Value: !GetAtt Repository.CloneUrlSsh
